export const INFO_FOOD_TREND = `FOOD TREND - CAMOUFLAGE PAINT DOESN'T LIKE PAYING TAXES. A KICKINGLY PRODIGIOUS PROFILE COULD PLEASE EVEN THE MOST DEMANDING FOLLOWER OF FREUD.`;
export const INFO_BEVERAGE_TREND = `BEVERAGE TREND - CAMOUFLAGE PAINT DOESN'T LIKE PAYING TAXES. A KICKINGLY PRODIGIOUS PROFILE COULD PLEASE EVEN THE MOST DEMANDING FOLLOWER OF FREUD.`;
export const INFO_EXCERCISE_TREND = `EXCERCISE TREND - PAINT DOESN'T LIKE PAYING TAXES. A KICKINGLY PRODIGIOUS PROFILE COULD PLEASE EVEN THE MOST DEMANDING FOLLOWER OF FREUD.`;

export const DIMS_BEVERAGE_TREND = {
  small: {
    columnWidth: 95,
    barGroupGap: 20,
    barGap: 2,
  },
  large: {
    columnWidth: 35,
    barGroupGap: 4,
    barGap: 1,
  },
};
export const DIMS_EXCERCISE_TREND = {
  small: {
    columnWidth: 100,
    columnGap: 10,
  },
  large: {
    columnWidth: 35,
    columnGap: 0,
  },
};
